### ISSUE TITLE
Pandoc Pluging do not find installed pandoc on Mac

### ISSUE THREAD

**Issue by Shirumipi** [Thereatra/inkdrop-pandoc#1]
Hello,

I am not sure if this is a real issue but after installed Pandoc via brew and checked that pandoc -v returned the installed version, I installed the pandoc Inldrop plugin but at each start of Inkdrop I got the error message saying that pandoc is not installed.

If you can help me on this, I would appreciate it.

**Comment by Thereatra** [comment]
As I didn't have a Mac available at the initial time of creation I've been unable to test it on MacOS so it is entirely possible that it simply does not recognize Pandoc on Mac. I do have a Mac now so I should be able to troubleshoot it soon-ish.

I see that there has been some discussion about this on the forum and I think I'll just adopt Lukas' approach of making the pandoc exec path a setting but I'll also try to see if I can get it to work automatically on Mac.

**Comment by Thereatra** [comment]
I have taken an initial look at this and have gotten the Pandoc detection working on MacOS by having a setting that allows the user to manually set the full path. Unfortunately I have also discovered that the current method of invoking Pandoc does not work on MacOS as it does not allow for using a custom Pandoc path.

**Comment by Thereatra** [comment]
@Shirumipi I have released a new version that should address this issue, at least it did with my limited testing on MacOS. This new version has an option that allow you to manually set the path for the Pandoc executable, similarly to what [Lukas described](https://forum.inkdrop.app/t/pandoc-plugin-do-not-find-pandoc/4436/6) but as part of the plugin settings instead of in the init file.

If you could try it out and see and report back that would be great.

**Comment by Shirumipi** [comment]
@Thereatra Thanks a million for your quick reply and fix.
I have just tried it and it works perfectly now!!

I wish you a wonderful day.
Shirumipi
